import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function addHeader(doc: jsPDF, title: string, docNumber?: string) {
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, 210, 35, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text(title, 14, 20);
  if (docNumber) {
    doc.setFontSize(10);
    doc.text(`Ref: ${docNumber}`, 14, 28);
  }
  doc.setTextColor(51, 65, 85);
}

function addFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Page ${pageNum} of ${totalPages}`, 105, 290, { align: "center" });
  doc.text("Generated by PSB-ERP", 196, 290, { align: "right" });
}

function addCompanyBlock(doc: jsPDF, y: number) {
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  doc.text("PSB Travel Agency", 14, y);
  doc.text("ERP Document System", 14, y + 5);
}

export function generateInvoicePDF(data: {
  invoice: { invoiceNumber: string; issueDate: Date | string; dueDate?: Date | string | null; subtotal: string | number; taxAmount: string | number; totalAmount: string | number; paidAmount: string | number; status: string; notes?: string | null };
  customer: { firstName: string; lastName: string; email?: string | null; phone?: string | null; address?: string | null } | null;
  items: { description: string; quantity: number; unitPrice: string | number; totalPrice: string | number }[];
  ticket?: { ticketNumber?: string | null; fromCity?: string | null; toCity?: string | null } | null;
}) {
  const doc = new jsPDF();
  addHeader(doc, "INVOICE", data.invoice.invoiceNumber);

  let y = 45;
  addCompanyBlock(doc, y);

  if (data.customer) {
    doc.setFontSize(10);
    doc.setTextColor(99, 102, 241);
    doc.text("BILL TO:", 120, y);
    doc.setTextColor(51, 65, 85);
    doc.text(`${data.customer.firstName} ${data.customer.lastName}`, 120, y + 5);
    if (data.customer.email) doc.text(data.customer.email, 120, y + 10);
    if (data.customer.phone) doc.text(data.customer.phone, 120, y + 15);
    if (data.customer.address) doc.text(data.customer.address, 120, y + 20);
  }

  y = 80;
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y - 5, 182, 20, "F");
  doc.setFontSize(9);
  doc.text(`Issue Date: ${String(data.invoice.issueDate)}`, 18, y + 5);
  if (data.invoice.dueDate) doc.text(`Due Date: ${String(data.invoice.dueDate)}`, 80, y + 5);
  doc.text(`Status: ${data.invoice.status.toUpperCase()}`, 150, y + 5);

  y = 110;
  autoTable(doc, {
    startY: y,
    head: [["Description", "Qty", "Unit Price", "Total"]],
    body: data.items.map(item => [
      item.description,
      String(item.quantity),
      `$${Number(item.unitPrice).toLocaleString()}`,
      `$${Number(item.totalPrice).toLocaleString()}`,
    ]),
    headStyles: { fillColor: [99, 102, 241], textColor: 255 },
    styles: { fontSize: 9, textColor: [51, 65, 85] },
    columnStyles: { 0: { cellWidth: 90 }, 1: { cellWidth: 25, halign: "center" }, 2: { cellWidth: 35, halign: "right" }, 3: { cellWidth: 35, halign: "right" } },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || y + 40;
  doc.setFontSize(10);
  doc.text("Subtotal:", 140, finalY + 10);
  doc.text(`$${Number(data.invoice.subtotal).toLocaleString()}`, 180, finalY + 10, { align: "right" });
  doc.text("Tax:", 140, finalY + 16);
  doc.text(`$${Number(data.invoice.taxAmount).toLocaleString()}`, 180, finalY + 16, { align: "right" });
  doc.setFontSize(12);
  doc.setTextColor(99, 102, 241);
  doc.text("TOTAL:", 140, finalY + 26);
  doc.text(`$${Number(data.invoice.totalAmount).toLocaleString()}`, 180, finalY + 26, { align: "right" });
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(9);
  doc.text(`Paid: $${Number(data.invoice.paidAmount).toLocaleString()}`, 140, finalY + 32);

  if (data.invoice.notes) {
    doc.setFontSize(8);
    doc.text(`Notes: ${data.invoice.notes}`, 14, finalY + 45);
  }

  addFooter(doc, 1, 1);
  return doc;
}

export function generateTicketVoucherPDF(data: {
  ticket: { ticketNumber?: string | null; passengerName?: string | null; fromCity?: string | null; toCity?: string | null; flightNumber?: string | null; airline?: string | null; departureDate?: Date | string | null; returnDate?: Date | string | null; class?: string | null; totalAmount: string | number; status: string };
  customer: { firstName: string; lastName: string; email?: string | null; phone?: string | null } | null;
}) {
  const doc = new jsPDF();
  addHeader(doc, "TICKET VOUCHER", data.ticket.ticketNumber || undefined);

  let y = 45;
  addCompanyBlock(doc, y);

  doc.setFontSize(10);
  doc.setTextColor(99, 102, 241);
  doc.text("PASSENGER:", 120, y);
  doc.setTextColor(51, 65, 85);
  const passengerName = data.ticket.passengerName || (data.customer ? `${data.customer.firstName} ${data.customer.lastName}` : "N/A");
  doc.text(passengerName, 120, y + 5);
  if (data.customer?.email) doc.text(data.customer.email, 120, y + 10);
  if (data.customer?.phone) doc.text(data.customer.phone, 120, y + 15);

  y = 75;
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, 182, 55, "F");
  doc.setFontSize(11);
  doc.setTextColor(99, 102, 241);
  doc.text("FLIGHT DETAILS", 18, y + 8);
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);

  const details = [
    ["From:", data.ticket.fromCity || "—", "To:", data.ticket.toCity || "—"],
    ["Airline:", data.ticket.airline || "—", "Flight:", data.ticket.flightNumber || "—"],
    ["Departure:", data.ticket.departureDate ? String(data.ticket.departureDate) : "—", "Return:", data.ticket.returnDate ? String(data.ticket.returnDate) : "—"],
    ["Class:", data.ticket.class || "—", "Status:", data.ticket.status.toUpperCase()],
  ];

  details.forEach((row, i) => {
    const ry = y + 18 + i * 10;
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(row[0], 18, ry);
    doc.setTextColor(51, 65, 85);
    doc.text(row[1], 45, ry);
    doc.setTextColor(100, 100, 100);
    doc.text(row[2], 100, ry);
    doc.setTextColor(51, 65, 85);
    doc.text(row[3], 125, ry);
  });

  y = 140;
  doc.setFontSize(14);
  doc.setTextColor(99, 102, 241);
  doc.text(`TOTAL: $${Number(data.ticket.totalAmount).toLocaleString()}`, 14, y);

  y = 160;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("Please arrive at the airport at least 3 hours before departure for international flights.", 14, y);
  doc.text("This voucher must be presented at check-in along with a valid passport.", 14, y + 5);
  doc.text("For changes or cancellations, please contact our office.", 14, y + 10);

  addFooter(doc, 1, 1);
  return doc;
}

export function generateDepositReceiptPDF(data: {
  deposit: { depositCode: string; amount: string | number; paymentMethod: string; referenceNumber?: string | null; status: string; approvedAt?: Date | string | null; createdAt: Date | string };
  customer: { firstName: string; lastName: string } | null;
  wallet: { walletCode?: string | null; balance: string | number } | null;
  approver?: { name?: string | null } | null;
}) {
  const doc = new jsPDF();
  addHeader(doc, "DEPOSIT RECEIPT", data.deposit.depositCode);

  let y = 45;
  addCompanyBlock(doc, y);

  y = 65;
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, 182, 70, "F");
  doc.setFontSize(11);
  doc.setTextColor(99, 102, 241);
  doc.text("RECEIPT DETAILS", 18, y + 8);
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);

  const rows = [
    ["Customer:", data.customer ? `${data.customer.firstName} ${data.customer.lastName}` : "—"],
    ["Amount:", `$${Number(data.deposit.amount).toLocaleString()}`],
    ["Payment Method:", data.deposit.paymentMethod],
    ["Reference:", data.deposit.referenceNumber || "—"],
    ["Wallet:", data.wallet?.walletCode || "—"],
    ["Status:", data.deposit.status.toUpperCase()],
    ["Date:", String(data.deposit.createdAt)],
  ];

  if (data.deposit.approvedAt) {
    rows.push(["Approved:", String(data.deposit.approvedAt)]);
    if (data.approver?.name) rows.push(["Approved By:", data.approver.name]);
  }

  rows.forEach((row, i) => {
    const ry = y + 18 + i * 8;
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    doc.text(row[0], 18, ry);
    doc.setTextColor(51, 65, 85);
    doc.text(row[1], 60, ry);
  });

  y = 155;
  doc.setFontSize(10);
  doc.setTextColor(99, 102, 241);
  doc.text("Thank you for your business!", 14, y);
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(8);
  doc.text("This receipt confirms the deposit has been credited to your wallet.", 14, y + 8);

  addFooter(doc, 1, 1);
  return doc;
}

export function generatePaymentVoucherPDF(data: {
  payment: { paymentNumber: string; amount: string | number; paymentMethod: string; paymentDate: Date | string; referenceNumber?: string | null; notes?: string | null };
  supplier: { companyName: string } | null;
  bill?: { billNumber: string; totalAmount: string | number } | null;
}) {
  const doc = new jsPDF();
  addHeader(doc, "PAYMENT VOUCHER", data.payment.paymentNumber);

  let y = 45;
  addCompanyBlock(doc, y);

  y = 65;
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y, 182, 60, "F");
  doc.setFontSize(11);
  doc.setTextColor(99, 102, 241);
  doc.text("PAYMENT DETAILS", 18, y + 8);
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);

  const rows = [
    ["Supplier:", data.supplier?.companyName || "—"],
    ["Amount:", `$${Number(data.payment.amount).toLocaleString()}`],
    ["Method:", data.payment.paymentMethod],
    ["Date:", String(data.payment.paymentDate)],
    ["Reference:", data.payment.referenceNumber || "—"],
  ];

  if (data.bill) {
    rows.push(["Bill:", data.bill.billNumber]);
    rows.push(["Bill Amount:", `$${Number(data.bill.totalAmount).toLocaleString()}`]);
  }

  rows.forEach((row, i) => {
    const ry = y + 18 + i * 8;
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    doc.text(row[0], 18, ry);
    doc.setTextColor(51, 65, 85);
    doc.text(row[1], 60, ry);
  });

  if (data.payment.notes) {
    y = 140;
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(`Notes: ${data.payment.notes}`, 14, y);
  }

  y = 170;
  doc.setFontSize(9);
  doc.text("Prepared By: ____________________", 14, y);
  doc.text("Approved By: ____________________", 110, y);

  addFooter(doc, 1, 1);
  return doc;
}
